[package]
name = "mini-paint-inventory"
version = "0.1.0"
authors = ["Julien Lopez <julien.lopez51@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
dioxus = { version = "0.6.3", features = ["fullstack", "router"] }
diesel = { version = "2.2.3", features = ["postgres", "r2d2"], optional = true }
# diesel-async = { version = "0.5.0", features = ["postgres"] }
getrandom = { version = "0.2", features = ["js"] }
dioxus-logger = "0.6.2"
dioxus-web = { version = "0.6.3", features = ["hydrate"], optional = true }
dotenv = "0.15.0"
dioxus-free-icons = { version = "0.9", features = [
    "material-design-icons-navigation",
], optional = true }

[features]
default = ["web"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web", "dioxus-web", "dioxus-free-icons"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]

server = ["dioxus/server", "dep:diesel"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
