services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=mini_paint_inventory
    volumes:
      - ./database_data:/var/lib/postgresql/data
    networks:
      - app_network
    command: [ "postgres", "-c", "log_statement=all" ]

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_password@postgres/mini_paint_inventory
    ports:
      - 8080:8080
    networks:
      - app_network
    depends_on:
      - postgres
    volumes:
      - ./:/app/

networks:
  app_network:
    driver: bridge
